//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalTimeSheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int DbId { get; set; }
        public string DbTitle { get; set; }
        public string DbDescription { get; set; }
        public Nullable<long> DbSpentTime { get; set; }
    }
}
